FROM python:3.11

WORKDIR /app

# Installation des dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copie du code
COPY . .

ENV PYTHONUNBUFFERED=1

# Lancement dynamique du bot
CMD ["sh", "-c", "${START_CMD:-python -u bot_multisymbol_v4.py}"]